export const RPC_METHOD_REGISTRY = {
  version: 1,
  defaultPolicy: {
    owner: 'rust-json-rpc',
    stability: 'internal',
    paramsValidation: 'record',
    requestSchema: 'deferred',
    responseSchema: 'deferred',
  },
  methods: [
    'health_check',
    'shutdown',
    'get_status',
    'get_disk_space',
    'get_system_resources',
    'get_launcher_version',
    'check_launcher_updates',
    'apply_launcher_update',
    'restart_launcher',
    'get_sandbox_info',
    'check_git',
    'check_brave',
    'check_setproctitle',
    'get_network_status',
    'get_library_status',
    'get_app_status',
    'get_available_versions',
    'get_installed_versions',
    'get_active_version',
    'get_default_version',
    'set_default_version',
    'switch_version',
    'install_version',
    'remove_version',
    'cancel_installation',
    'get_installation_progress',
    'validate_installations',
    'get_version_status',
    'get_version_info',
    'get_release_size_info',
    'get_release_size_breakdown',
    'calculate_release_size',
    'calculate_all_release_sizes',
    'has_background_fetch_completed',
    'reset_background_fetch_flag',
    'get_github_cache_status',
    'check_version_dependencies',
    'install_version_dependencies',
    'get_release_dependencies',
    'is_patched',
    'toggle_patch',
    'get_models',
    'refresh_model_index',
    'refresh_model_mappings',
    'import_model',
    'download_model_from_hf',
    'start_model_download_from_hf',
    'get_model_download_status',
    'cancel_model_download',
    'pause_model_download',
    'resume_model_download',
    'list_model_downloads',
    'list_interrupted_downloads',
    'recover_download',
    'resume_partial_download',
    'search_hf_models',
    'get_hf_download_details',
    'get_related_models',
    'search_models_fts',
    'import_batch',
    'import_external_diffusers_directory',
    'classify_model_import_paths',
    'lookup_hf_metadata_for_file',
    'lookup_hf_metadata_for_bundle_directory',
    'detect_sharded_sets',
    'validate_file_type',
    'get_embedded_metadata',
    'get_library_model_metadata',
    'resolve_model_execution_descriptor',
    'refetch_model_metadata_from_hf',
    'adopt_orphan_models',
    'import_model_in_place',
    'scan_shared_storage',
    'get_inference_settings',
    'update_inference_settings',
    'update_model_notes',
    'resolve_model_dependency_requirements',
    'audit_dependency_pin_compliance',
    'list_models_needing_review',
    'submit_model_review',
    'reset_model_review',
    'generate_model_migration_dry_run_report',
    'execute_model_migration',
    'list_model_migration_reports',
    'delete_model_migration_report',
    'prune_model_migration_reports',
    'set_hf_token',
    'clear_hf_token',
    'get_hf_auth_status',
    'is_comfyui_running',
    'stop_comfyui',
    'launch_comfyui',
    'launch_ollama',
    'stop_ollama',
    'is_ollama_running',
    'launch_torch',
    'stop_torch',
    'is_torch_running',
    'open_path',
    'open_url',
    'open_active_install',
    'ollama_list_models',
    'ollama_create_model',
    'ollama_delete_model',
    'ollama_load_model',
    'ollama_unload_model',
    'ollama_list_running',
    'torch_list_slots',
    'torch_load_model',
    'torch_unload_model',
    'torch_get_status',
    'torch_list_devices',
    'torch_configure',
    'get_link_health',
    'clean_broken_links',
    'remove_orphaned_links',
    'get_links_for_model',
    'delete_model_with_cascade',
    'preview_model_mapping',
    'apply_model_mapping',
    'sync_models_incremental',
    'sync_with_resolutions',
    'get_cross_filesystem_warning',
    'get_file_link_count',
    'check_files_writable',
    'set_model_link_exclusion',
    'get_link_exclusions',
    'get_version_shortcuts',
    'get_all_shortcut_states',
    'toggle_menu',
    'toggle_desktop',
    'menu_exists',
    'desktop_exists',
    'install_icon',
    'create_menu_shortcut',
    'create_desktop_shortcut',
    'remove_menu_shortcut',
    'remove_desktop_shortcut',
    'start_model_conversion',
    'get_conversion_progress',
    'cancel_model_conversion',
    'list_model_conversions',
    'check_conversion_environment',
    'setup_conversion_environment',
    'get_supported_quant_types',
    'get_backend_status',
    'setup_quantization_backend',
    'get_plugins',
    'get_plugin',
    'check_plugin_health',
    'get_custom_nodes',
    'install_custom_node',
    'update_custom_node',
    'remove_custom_node',
  ] as const,
} as const;

export type RpcMethodName = (typeof RPC_METHOD_REGISTRY.methods)[number];

export type RpcParamsValidationPolicy = 'record' | 'empty-record';

export const RPC_METHOD_PARAM_VALIDATION = {
  get_status: 'empty-record',
  get_disk_space: 'empty-record',
  get_system_resources: 'empty-record',
  get_all_shortcut_states: 'empty-record',
  has_background_fetch_completed: 'empty-record',
  reset_background_fetch_flag: 'empty-record',
  get_models: 'empty-record',
  refresh_model_index: 'empty-record',
  scan_shared_storage: 'empty-record',
  list_model_downloads: 'empty-record',
  list_interrupted_downloads: 'empty-record',
  get_hf_auth_status: 'empty-record',
  launch_comfyui: 'empty-record',
  stop_comfyui: 'empty-record',
  launch_ollama: 'empty-record',
  stop_ollama: 'empty-record',
  launch_torch: 'empty-record',
  stop_torch: 'empty-record',
  get_plugins: 'empty-record',
} as const satisfies Partial<Record<RpcMethodName, RpcParamsValidationPolicy>>;

const RPC_METHOD_PARAM_VALIDATION_BY_METHOD: Partial<
  Record<RpcMethodName, RpcParamsValidationPolicy>
> = RPC_METHOD_PARAM_VALIDATION;

export function getRpcParamsValidationPolicy(method: RpcMethodName): RpcParamsValidationPolicy {
  return RPC_METHOD_PARAM_VALIDATION_BY_METHOD[method] ?? RPC_METHOD_REGISTRY.defaultPolicy.paramsValidation;
}
